swagger: "2.0"
info:
  version: "0.0.1"
  title: Baseurl /showme/v1
        
  
# during dev, should point to your local machine
host: localhost:80
# basePath prefixes all resource paths 
basePath: /showme/v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/x-www-form-urlencoded
  - multipart/form-data
# format of the responses to the client (Accepts)
produces:
  - application/json
  - application/x-www-form-urlencoded
  - multipart/form-data
paths:
  /user:
    # binds a127 app logic to a route
    x-swagger-router-controller: user
    post:
      description: API for register user.
      # used as the method name of the controller
      operationId: registerUser
      parameters:
        - name: email
          in: formData
          description: The user's email.
          required: true
          type: string
          format: email
        - name: pwd
          in: formData
          description: The user's password.
          required: true
          type: string
        - name: firstname
          in: formData
          description: The user's first name.
          required: true
          type: string
        - name: lastname
          in: formData
          description: The user's last name.
          required: true
          type: string
        - name: dob
          in: formData
          description: The user's day of birth. (yyyy-mm-dd)
          required: true
          type: string
          format: date
        - name: device_uiid
          in: formData
          description: The user's device token.
          required: true
          type: string 
      responses:
        "201":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/BaseSuccessRespone"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: API for update user profiles.
      operationId: updateUserProfiles
      parameters:
        - name: user
          in: body
          description: The user's info.
          required: true
          schema:
            $ref: "#/definitions/updateProfilesParams" 
      responses:
        "201":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/BaseSuccessRespone"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/role:
    # binds a127 app logic to a route
    x-swagger-router-controller: user
    put:
      description: API for update user's role.
      # used as the method name of the controller
      operationId: updateRole
      parameters:
        - name: user_id
          in: formData
          description: The user's id.
          required: true
          type: string
        - name: role
          in: formData
          description: The current role of user ("user" or "leader").
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/BaseSuccessRespone"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"           
  /login:
    # binds a127 app logic to a route
    x-swagger-router-controller: user
    post:
      description: API for login.
      # used as the method name of the controller
      operationId: login
      parameters:
        - name: email
          in: formData
          description: The user's email.
          required: true
          type: string
          format: email
        - name: pwd
          in: formData
          description: The user's password.
          required: true
          type: string
        - name: device_uiid
          in: formData
          description: The user's device token.
          required: true
          type: string  
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/BaseSuccessRespone"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /leaders/{user_id}:
    x-swagger-router-controller: leader
    get:
      description: API for get leaders information by id.
      # used as the method name of the controller
      operationId: getLeaderInfo
      parameters:
        - name: user_id
          in: path
          description: The user's id.
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/BaseSuccessRespone"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"  
  /leaders/location:
    # binds a127 app logic to a route
    x-swagger-router-controller: leader
    get:
      description: API for get leaders location in range.
      # used as the method name of the controller
      operationId: leaderLocation
      parameters:
        - name: radius
          in: query
          description: radius which user input.
          required: false
          type: number
        - name: lng
          in: query
          description: longitude which user input.
          required: false
          type: number
        - name: lat
          in: query
          description: lattitude which user input.
          required: false
          type: number    
        - name: address
          in: query
          description: address which user input.
          required: false
          type: number  
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/BaseSuccessRespone"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: API for update leaders location.
      # used as the method name of the controller
      operationId: updateLocation
      parameters:
        - name: user_id
          in: formData
          description: The user's id.
          required: true
          type: string
        - name: address
          in: formData
          description: The user address.
          required: true
          type: string  
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/BaseSuccessRespone"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /leaders/active:
    x-swagger-router-controller: leader  
    put:
      description: API for update leaders status.
      # used as the method name of the controller
      operationId: updateStatus
      parameters:
        - name: user_id
          in: formData
          description: The user's id.
          required: true
          type: string
        - name: active
          in: formData
          description: The current status.
          required: true
          type: boolean   
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/BaseSuccessRespone"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  BaseSuccessRespone:
    required:
      - message
      - returnCode
    properties:
      message:
        type: string
      returnCode:
        type: number
      data:
        type: object
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
      returnCode:
        type: number
      data:
        type: object
        
  updateProfilesParams:
    description: user updated info.
    properties:
      user_id: 
        type: string
      avatar:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      country:
        type: string
      description:
        type: string
      fee_per_hour:
        type: string
      sex:
        type: string
      dob:
        description: format (yyyy/mm/dd).
        type: string
        format: date
      email: 
        type: string
      address:
        type: string
      phone:
        type: string
    required:
      - user_id
      # - firstname
      # - lastname
      # - country
      # - description
      # - sex
      # - dob
      # - email
      # - address
      # - phone
  codeReturn:
    description: leader status info object.
    properties:
      error_code:
        type: number
        description: a 1000
      success_code:
        type: number
        description: a 2000
      create_code:
        type: number
        description: a 2002  
      database_error_code:
        type: number
        description: a 1001  
      quickblox_create_code:
        type: number
        description: a 1002  
      no_token_code:
        type: number
        description: a 1003  
      token_expire_code:
        type: number
        description: a 1004  
      token_error_code:
        type: number
        description: a 1005  
  # DeviceInfo:
  #   description: DeviceInfo
  #   properties:
  #     device_uiid:
  #       type: string
  #     os:
  #       type: string        
  
